services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # mapping local /server to the container server
      # source:/destination/place
      - ./server:/home/apiUser/app/server
    environment:
      - PORT=3000
    links:
      - mongodb
      - mongoseed
    env_file:
      - path: ./.env
        required: false

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./server:/home/apiUser/app/server
    depends_on:
      - server

  mongodb:
    image: mongo:8
    command: mongod
    ports:
      - "27017:27017"

  mongoseed:
    build: ./config/mongoseed
    depends_on:
      mongodb:
        condition: service_started
